name: goal_timer
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.2+10

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: '>=3.29.0'

dependencies:
  app_tracking_transparency: ^2.0.6
  connectivity_plus: ^7.0.0
  crypto: ^3.0.3
  cupertino_icons: '1.0.8'
  dio: ^5.9.0
  firebase_analytics: ^12.1.0
  firebase_core: ^4.3.0
  firebase_crashlytics: ^5.0.6
  fl_chart: '0.71.0'
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_local_notifications: ^19.5.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.1.0
  formz: ^0.8.0
  freezed_annotation: ^3.0.0
  frontend_server_client: '4.0.0'
  get: ^4.7.3
  google_sign_in: ^7.2.0
  in_app_review: ^2.0.9
  intl: any
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  local_auth: ^3.0.0
  logger: ^2.6.2
  path: '1.9.1'
  path_provider: ^2.1.5
  purchases_flutter: ^9.0.0
  riverpod_annotation: ^4.0.0
  shared_preferences: ^2.2.2
  sign_in_with_apple: ^7.0.1
  sqflite: '2.4.2'
  supabase_flutter: '2.3.4'
  timezone: ^0.10.1
  url_launcher: ^6.3.0
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.7.1
  custom_lint: ^0.8.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.0
  json_serializable: ^6.9.0
  mockito: ^5.4.4
  mocktail: ^1.0.4
  riverpod_generator: ^4.0.0+1
  sqflite_common_ffi: ^2.3.6
  tanzam_lints:
    path: tanzam_lints

flutter:
  uses-material-design: true
  
  # 環境変数ファイルのアセット登録
  assets:
    - .env
    - assets/icons/

# アプリアイコン設定
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/goal_timer_app_icon.png"
  adaptive_icon_background: "#1976D2"
  adaptive_icon_foreground: "assets/icons/goal_timer_app_icon.png"
