name: tanzam_lints
description: Custom lint rules for Goal Timer App
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.4

dependencies:
  analyzer: ^6.0.0
  analyzer_plugin: ^0.11.0
  custom_lint_builder: ^0.7.0
